import { useEffect, useState } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { addProjectSource, createProjectReview, getProject, getProjectTimeline } from '../api';

export default function ProjectDetailPage() {
  const { projectId } = useParams(); const navigate = useNavigate(); const [project, setProject] = useState(null); const [tab, setTab] = useState('overview'); const [error, setError] = useState(''); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [url, setUrl] = useState(''); const [timeline, setTimeline] = useState([]);
  async function load() { try { const p = await getProject(projectId); setProject(p); setTimeline((await getProjectTimeline(projectId)).events || []); } catch (e) { setError(e.message); } }
  useEffect(() => { load(); }, [projectId]);
  async function addSource(e) { e.preventDefault(); try { await addProjectSource(projectId, { title, content, source_url: url, source_type: url ? 'link' : 'prd_text', is_prd: true }); setTitle(''); setContent(''); setUrl(''); await load(); } catch (e) { setError(e.message); } }
  async function run(sourceId) { try { const r = await createProjectReview(projectId, { source_id: sourceId }); navigate(`/run/${r.run_id}`); } catch (e) { setError(e.message); } }
  if (!project) return <main className="panel">正在加载项目…</main>;
  const tabs = [['overview','概览'],['sources','资料'],['reviews','PRD 与评审'],['delivery','协作与交付']];
  return <main className="stack project-space-page"><header className="page-header"><div><Link to="/" className="inline-meta">← 所有项目</Link><p className="eyebrow">Project Space</p><h1>{project.name}</h1><p className="page-lead">{project.description || '添加资料后即可开始可追溯的 PRD 评审。'}</p></div></header><nav className="workbench-tabs">{tabs.map(([id,label]) => <button key={id} className={`workbench-tab${tab === id ? ' workbench-tab-active' : ''}`} onClick={() => setTab(id)}>{label}</button>)}</nav>{error ? <p className="form-error">{error}</p> : null}{tab === 'overview' ? <section className="workspace-grid"><article className="panel"><h2>当前状态</h2><p className="metric-value">{project.sources.length} <small>份资料</small></p><p>将资料与每次评审保留在同一个项目上下文。</p></article><article className="panel"><h2>最近活动</h2><ul className="stack-list">{timeline.slice(0,5).map((e,i)=><li key={i}><strong>{e.kind === 'review' ? '发起评审' : '添加资料'}</strong><p>{e.label}</p></li>)}{!timeline.length ? <li>暂无活动</li> : null}</ul></article></section> : null}{tab === 'sources' ? <section className="workspace-grid"><form className="panel stack" onSubmit={addSource}><h2>添加项目资料</h2><label className="field"><span>标题</span><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="会员改版 PRD" /></label><label className="field"><span>正文</span><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="粘贴 PRD、会议纪要或补充要求" /></label><label className="field"><span>飞书或文档链接</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." /></label><button className="primary-button">保存为新版本</button></form><section className="panel"><h2>已连接资料</h2><ul className="stack-list">{project.sources.map(s=><li key={s.id}><strong>{s.title}</strong><p>{s.source_type} · v{s.version}</p>{s.source_url ? <a href={s.source_url}>打开原文</a> : null}</li>)}{!project.sources.length?<li>暂无资料。</li>:null}</ul></section></section> : null}{tab === 'reviews' ? <section className="panel"><div className="panel-header"><div><h2>PRD 与评审</h2><p>选择一份资料发起新的审查。</p></div></div><ul className="stack-list">{project.sources.map(s=><li key={s.id}><strong>{s.title}</strong><div className="action-row"><button className="primary-button" onClick={()=>run(s.id)}>开始评审</button></div></li>)}{project.runs.map(r=><li key={r.run_id}><Link to={`/run/${r.run_id}`}><strong>{r.run_id}</strong></Link><p>查看此次评审结果、澄清和产物。</p></li>)}</ul></section> : null}{tab === 'delivery' ? <section className="panel"><h2>协作与交付</h2><p>在具体评审详情中处理澄清、修订、roadmap 和 handoff。所有产物会自动保留在该项目的运行记录中。</p>{project.runs[0] ? <Link className="primary-button" to={`/run/${project.runs[0].run_id}`}>打开最新评审</Link> : null}</section> : null}</main>;
}
