import { useEffect, useState } from 'react';
import { createProviderConnection, fetchProviderCatalog, listProviderConnections, testProviderConnection } from '../api';

export default function ProviderSettingsPage() {
  const [catalog,setCatalog]=useState([]),[connections,setConnections]=useState([]),[master,setMaster]=useState(false),[provider,setProvider]=useState('openai'),[name,setName]=useState(''),[apiKey,setApiKey]=useState(''),[baseUrl,setBaseUrl]=useState(''),[message,setMessage]=useState('');
  async function load(){try{const [c,x]=await Promise.all([fetchProviderCatalog(),listProviderConnections()]);setCatalog(c.providers||[]);setConnections(x.connections||[]);setMaster(x.master_key_configured)}catch(e){setMessage(e.message)}}
  useEffect(()=>{load()},[]); const selected=catalog.find(x=>x.id===provider);
  async function submit(e){e.preventDefault();try{await createProviderConnection({name:name||`${provider} connection`,provider,api_key:apiKey,base_url:baseUrl});setMessage('连接已保存；密钥不会再显示。');setApiKey('');setName('');await load()}catch(err){setMessage(err.message)}}
  async function test(id){try{setMessage((await testProviderConnection(id)).message);await load()}catch(e){setMessage(e.message)}}
  return <main className="stack project-space-page"><header className="page-header"><div><p className="eyebrow">Settings</p><h1>模型连接</h1><p className="page-lead">你的密钥仅加密保存在当前自托管实例中，不会写入项目或评审产物。</p></div></header>{!master?<p className="feedback-banner feedback-error">保存云端 Provider 前，请在 `.env` 中设置 `MARRDP_SECRETS_MASTER_KEY`（Fernet 密钥）。Ollama 无需密钥。</p>:null}<section className="workspace-grid"><form className="panel stack" onSubmit={submit}><h2>新建连接</h2><label className="field"><span>Provider</span><select value={provider} onChange={e=>setProvider(e.target.value)}>{catalog.map(p=><option key={p.id} value={p.id}>{p.label}{p.available?'':'（需安装依赖）'}</option>)}</select></label><label className="field"><span>显示名称</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="我的模型连接" /></label>{selected?.fields.includes('api_key')?<label className="field"><span>API Key</span><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} required={selected?.requires_api_key}/></label>:null}<label className="field"><span>Base URL（可选）</span><input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} /></label><button className="primary-button">保存连接</button></form><section className="panel"><h2>已保存的连接</h2><ul className="stack-list">{connections.map(c=><li key={c.id}><strong>{c.name}</strong><p>{c.provider} · {c.status} · {c.api_key_masked || '本地连接'}</p><button className="ghost-button" onClick={()=>test(c.id)}>验证配置</button></li>)}{!connections.length?<li>尚未配置连接。</li>:null}</ul>{message?<p className="panel-copy">{message}</p>:null}</section></section></main>;
}
